// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: service.proto

package gogrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HTTPRequestsService_RequestHandler_FullMethodName = "/HTTPRequestsService/RequestHandler"
)

// HTTPRequestsServiceClient is the client API for HTTPRequestsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HTTPRequestsServiceClient interface {
	RequestHandler(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*Response, error)
}

type hTTPRequestsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHTTPRequestsServiceClient(cc grpc.ClientConnInterface) HTTPRequestsServiceClient {
	return &hTTPRequestsServiceClient{cc}
}

func (c *hTTPRequestsServiceClient) RequestHandler(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, HTTPRequestsService_RequestHandler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HTTPRequestsServiceServer is the server API for HTTPRequestsService service.
// All implementations must embed UnimplementedHTTPRequestsServiceServer
// for forward compatibility.
type HTTPRequestsServiceServer interface {
	RequestHandler(context.Context, *UserRequest) (*Response, error)
	mustEmbedUnimplementedHTTPRequestsServiceServer()
}

// UnimplementedHTTPRequestsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHTTPRequestsServiceServer struct{}

func (UnimplementedHTTPRequestsServiceServer) RequestHandler(context.Context, *UserRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestHandler not implemented")
}
func (UnimplementedHTTPRequestsServiceServer) mustEmbedUnimplementedHTTPRequestsServiceServer() {}
func (UnimplementedHTTPRequestsServiceServer) testEmbeddedByValue()                             {}

// UnsafeHTTPRequestsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HTTPRequestsServiceServer will
// result in compilation errors.
type UnsafeHTTPRequestsServiceServer interface {
	mustEmbedUnimplementedHTTPRequestsServiceServer()
}

func RegisterHTTPRequestsServiceServer(s grpc.ServiceRegistrar, srv HTTPRequestsServiceServer) {
	// If the following call pancis, it indicates UnimplementedHTTPRequestsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HTTPRequestsService_ServiceDesc, srv)
}

func _HTTPRequestsService_RequestHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPRequestsServiceServer).RequestHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPRequestsService_RequestHandler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPRequestsServiceServer).RequestHandler(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HTTPRequestsService_ServiceDesc is the grpc.ServiceDesc for HTTPRequestsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HTTPRequestsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HTTPRequestsService",
	HandlerType: (*HTTPRequestsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestHandler",
			Handler:    _HTTPRequestsService_RequestHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
